import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    id("base")
    id("com.fussionlabs.gradle.go-plugin") version("0.6.7")
    id("com.bmuschko.docker-remote-api") version("9.4.0")
}

version = "1.0.0"
val imageRepository = "dm0275/secret-replicator-controller"
val imageTags = listOf("$imageRepository:latest", "$imageRepository:$version")

go {
    os = listOf("linux")
    arch = listOf("amd64")
    goVersion = "1.21.10"
}

docker {
    registryCredentials {
        username = System.getenv("DOCKER_USERNAME")
        password = System.getenv("DOCKER_PASSWORD")
    }
}

tasks.register("dockerBuildImage", DockerBuildImage::class) {
    dependsOn("build")
    inputDir.set(rootDir)
    images.addAll(imageTags)
}