# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_run:
    workflows:
      - CI
    branches: main
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Publish the image
      - name: Publish Image
        env:
          DOCKER_USERNAME: ${{ secrets.dockerUsername }}
          DOCKER_PASSWORD: ${{ secrets.dockerPassword }}
        run: ./gradlew dockerPushImage